<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>ArrayCamera.Core</RootNamespace>
    <AssemblyName>ArrayCamera.Core</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Authors>Array Test System Team</Authors>
    <Company>光电探测传感系统研究组</Company>
    <Product>Array Test System Host Software</Product>
    <Version>1.0.0</Version>
    <Description>高性能热力图渲染核心库</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

</Project>
